#spring:
#  r2dbc:
#    url: r2dbc:pool:postgres://localhost:5432/animus
#    username: ${POSTGRES_USER:jung}
#    password: ${POSTGRES_PASSWORD:secret}
#    pool:
#      validation-query: SELECT 1
#      max-idle-time: 30m
#    properties:
#      sslMode: DISABLE
#      schema: main
